creation_rules:
  - path_regex: values\.yaml$
    pgp: EE8F70A28E7C9311F52B77DA9C23BC360AC0E075
    encrypted_regex: ^(data|stringData)$

# creation_rules:
#   - path_regex: .*values.yaml$
#     encrypted_regex: "^(password)$"
#     key_groups:
#       - age:
#          - age10fq6202yhpg3nh0ce32dhz8w64g2xa8lkwux0uzuafnz3ywguuvqqyf68r