apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: clickhouse
  namespace: clickhouse
resources:
  - helmrepo.yaml
  - release.yaml
  - namespace.yaml
secretGenerator:
  - name: clickhouse-auth
    files:
      # - values.yaml=./clickhouse/auth.yaml
configurations:
  - kustomizeconfig.yaml
