apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sops-encrypted
  namespace: clickhouse
spec:
  interval: 2m
  path: "./"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
resources:
  - helmrepo.yaml
  - release.yaml
  - namespace.yaml
secretGenerator:
  - name: clickhouse-auth
    namespace: clickhouse
    files:
      - values.yaml=auth.yaml
configurations:
  - kustomizeconfig.yaml
