apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - release.yaml
  - namespace.yaml
secretGenerator:
  - name: clickhouse-auth
    namespace: clickhouse
    files:
      - values.yaml=../credentials/auth.yaml
configurations:
  - kustomizeconfig.yaml
