apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickhouse
resources:
  - ./clickhouse/helmrepo.yaml
  - ./clickhouse/release.yaml
  - ./clickhouse/namespace.yaml
secretGenerator:
  - name: clickhouse-auth
    files:
      # - values.yaml=./clickhouse/auth.yaml
configurations:
  - ./clickhouse/kustomizeconfig.yaml
