apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  interval: 5m
  chart:
    spec:
      chart: clickhouse
      version: 8.0.6
      sourceRef:
        kind: OCIRepository
        name: clickhouse
        namespace: flux-system
      valuesFiles:
        - values.yaml