apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  chart: clickhouse
  version: 8.0.6
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: clickhouse
    namespace: flux-system
    # version: 8.0.6
    valuesFiles:
      - values.yaml