creation_rules:
  - path_regex: ./credentials/auth.yaml$
    encrypted_regex: "^(data|stringData|secret|secureJsonData|password|stringPassword)$" # You can add required regex here
    age: age10fq6202yhpg3nh0ce32dhz8w64g2xa8lkwux0uzuafnz3ywguuvqqyf68r