apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clickhouse/helmrepo.yaml
  - clickhouse/release.yaml
  - clickhouse/namespace.yaml
secretGenerator:
  - name: clickhouse-auth
    files:
      - auth.yaml
configurations:
  - kustomizeconfig.yaml
