apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sops-encrypted
  namespace: clickhouse
spec:
  interval: 2m
  path: "./clusters/home"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age