# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   # Add resources to be included in the kustomization
#   # For example:
#   - flux-system/
#   # - infrastructure/
#   - applications/
