apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: clickhouse
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    # Values are loaded from the values.yaml file
    replicaCount: 2
    clusterName: "clickhouse-cluster1"
    logLevel: "warning"
    persistence:
      size: 1Gi
    resourcesPreset: "small"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
    zookeeper:
      enabled: false
    keeper:
      enabled: true
    distributeReplicasByZone: true
    shards: 1
    auth:
      username: default
      password: "HmLdpo39fRRd441D"
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

