apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-secret
    namespace: clickhouse
stringData:
    username: ENC[AES256_GCM,data:yydrN/7rDg==,iv:jQqK08Fxu76pxaHagQfrIr6UJqN/lPrOXKjE77fuBX0=,tag:MSEizuhw3pzGZI9rZ0J40Q==,type:str]
    password: ENC[AES256_GCM,data:POg65sPFR5ES2FlV9nYZ7w==,iv:9VvUtL6QfJjR8tVjhxbZxBHKxTybFPyFNziuckmIoX4=,tag:bK7JperOQsEGg0gOTl+GrA==,type:str]
sops:
    age:
        - recipient: age10fq6202yhpg3nh0ce32dhz8w64g2xa8lkwux0uzuafnz3ywguuvqqyf68r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRjZ5SzVyRjZQUXZ5S3Z4
            OHRSZm9YNUpWbjFrSDdKSW5SeHJ4UkQ1L0RNCktXZ2ZOVjQvbThuem45K05yclVh
            WWk5ZWExS3NUMWRkRzZlNE1oSnZLM1UKLS0tIFFaVWNlK2FzK1dnbDdocmkyclF1
            b2lYOTNnQS8yVURzT2l4MkFFYjJXakUK0mU1OftyUmbod6++bDTauc6pfq5FL9W9
            I3Jw+w01fyAhR+vYzuClKNMVFm1cAN24YvUeMSNQDoWNUaDZcAUETw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-28T09:39:20Z"
    mac: ENC[AES256_GCM,data:j+cukwz2grA1IR0IVv2iK1I+bZnZc03/wbdClzOH6RzQaDyegyVunonz0obmHL7lifGeObxjZhPlmyAVF4aWTa0JdzHittJjoVlzFDTn0UlFtk4KmG/yzrxygc5BidqD/i9rKMEtdq5mI1Ki9wwMdeYsshXTE6CUgwevjFetxXM=,iv:e/XpJebCdGhCObdMV362VoGsD+9VvFdSlpMs9T03JdE=,tag:9CfDJc9Cz2bzejPSrySSyg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.1
